network.host: 0.0.0.0

# bootstrap.memory_lock: true

### Cluster settings
# cluster.name: go_elastic_starter_cluster
# node.name: goserach_node
# discovery.zen.ping.unicast.hosts: ['elasticsearch01', 'elasticsearch02', 'elasticsearch03']
# ## This setting must be set to a quorum of your master eligible nodes.
discovery.zen.minimum_master_nodes: 2

### x-pack functions
# xpack.security.enabled: false
# xpack.monitoring.enabled: true
# xpack.graph.enabled: true
# xpack.watcher.enabled: false